# Generated by Django 6.0.5 on 2026-08-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='კურსის დაწყების თარიღი და დრო', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default='', help_text='რას ისწავლის მოსწავლე ამ კურსზე (თემები/გეგმა)'),
        ),
    ]
