# Generated by Django 6.0.5 on 2026-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_studenthistoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', help_text='მაგ: ვისთვის არის განკუთვნილი ეს კოდი (არასავალდებულო, მხოლოდ ადმინისთვის).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'მასწავლებლის წვდომის კოდი',
                'verbose_name_plural': 'მასწავლებლის წვდომის კოდები',
            },
        ),
    ]
